---
jobs:
  - name: container-limits-example
    public: true
    plan:
      # Example 1: Container limits in task config
      - task: task-with-config-limits
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          container_limits:
            cpu: 512 # CPU shares
            memory: 134217728 # 128MB in bytes
          run:
            path: sh
            args:
              - -c
              - |
                  echo "Checking memory limit..."
                  cat /sys/fs/cgroup/memory/memory.limit_in_bytes 2>/dev/null || cat /sys/fs/cgroup/memory.max 2>/dev/null
        assert:
          stdout: "134217728"
