resource_types:
  - name: mock
    type: registry-image
    source:
      repository: concourse/mock-resource
resources:
  - name: test-resource
    type: mock
    source:
      force_version: "2025"
jobs:
  - name: handle-resources
    public: true
    plan:
      - get: test-resource
      - task: check-version
        config:
          platform: linux
          inputs:
            - name: test-resource
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: sh
            args: ["-c", "cat ./test-resource/version"]
        assert:
          stdout: "2025"
      - put: test-resource
        params: { version: 2026 }
      - task: check-updated-version
        config:
          platform: linux
          inputs:
            - name: test-resource
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: sh
            args: ["-c", "cat ./test-resource/version"]
        assert:
          stdout: "2026"
    assert:
      execution:
        - check-test-resource
        - get-test-resource
        - check-version
        - put-test-resource
        - get-test-resource
        - check-updated-version
