# Test version: every with time-resource (docker only)
# This test requires docker driver and uses the time-resource which produces
# genuinely new versions over time.

resource_types:
  - name: time
    type: registry-image
    source:
      repository: concourse/time-resource

resources:
  - name: timer
    type: time
    source:
      interval: 1s

jobs:
  - name: process-time
    plan:
      - get: timer
        version: every
      - task: show-time
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          inputs:
            - name: timer
          run:
            path: sh
            args: ["-c", "cat timer/input && echo"]
        assert:
          code: 0
