run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - exhaustruct # allow zero values for
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gomoddirectives
    - ireturn
    - lll # too long of line
    - maintidx # complexity rule
    - revive # too many rules
    - tagliatelle # disable because pipeline yaml uses underscores
    - tenv
