run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - exportloopref
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gomoddirectives
    - ireturn
    - revive
    - tagliatelle
