version: 3

tasks:
  build:
    cmds:
      - task: build:static
      - go generate ./...
  build:static:
    dir: server/static
    cmds:
      - npm install
      - npm run build
  fmt:
    cmds:
      - deno fmt --ignore=server/templates/,backwards/bundle.js,server/static/dist/bundle.js .
      - deno lint --rules-exclude=no-window,no-process-global,no-node-globals --ignore=server/static/dist/,server/templates/,backwards/bundle.js .
      - deno check backwards/src/ examples/both/
      - shellcheck bin/*.sh
      - shfmt -w bin/
      - gofmt -w .
      - golangci-lint run ./... --fix
  default:
    cmds:
      - task: build
      - task: fmt
      - task: cleanup
      - defer: { task: cleanup }
      - go test -race ./... -count=1 -parallel=1
      - task: test:e2e
  test:e2e:
    dir: e2e
    cmds:
      - rm -f e2e-test.db
      - npx playwright test
  test:vz:
    desc: Run VZ driver tests with codesigning
    cmds:
      - |
          cat > entitlements.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>com.apple.security.virtualization</key>
              <true/>
          </dict>
          </plist>
          EOF
      - go test -c -o vz.test ./orchestra/vz
      - codesign -s - -f --entitlements entitlements.plist ./vz.test
      - ./vz.test -test.v
      - rm -f vz.test entitlements.plist
  # Watch source files only. Exclude generated bundles in server/static/dist and node_modules
  server: "wgo -file .html -file .ts -file .go -dir server/static/src go generate ./... :: go run main.go server --storage sqlite://test.db"

  # Benchmark tasks
  bench:
    desc: Run all Go benchmarks (micro + pipeline)
    cmds:
      - go test -bench=. -benchmem -count=3 ./runtime/... ./storage/... ./examples/...

  bench:k6:
    desc: Run k6 API load benchmarks (starts server automatically)
    cmds:
      - ./bin/k6-with-server.sh run benchmarks/api_load.js

  bench:k6:smoke:
    desc: Quick k6 smoke test (starts server automatically)
    cmds:
      - ./bin/k6-with-server.sh run --vus 1 --duration 10s benchmarks/api_load.js

  cleanup:
    desc: Remove leaked Docker containers and volumes
    cmds:
      - ./bin/cleanup.sh

  bump:
    desc: Bump all Go and npm dependencies to latest versions
    cmds:
      - echo "Bumping Go dependencies..."
      - go get -u ./...
      - go mod tidy
      - echo "Bumping npm dependencies in e2e..."
      - cd e2e && npm update
      - echo "Bumping npm dependencies in packages/ci..."
      - cd packages/ci && npm update
      - echo "Bumping npm dependencies in examples..."
      - cd examples && npm update
      - echo "Bumping npm dependencies in server/static..."
      - cd server/static && npm update
      - echo "All dependencies bumped! Run 'task' to test."
