version: 3

tasks:
  default:
    cmds:
      - deno fmt .
      - gofmt -w .
      - golangci-lint run ./... --fix
      - go test -race ./...
  cleanup:
    cmds:
      - fly machines ls -a $FLY_APP_NAME --json | jq .[].id -r | xargs -I {} fly machines destroy -f -a $FLY_APP_NAME {}
      - docker ps -aq | xargs -I {} docker rm -f {}
