version: 3

tasks:
  default:
    cmds:
      - deno fmt .
      - gofmt -w .
      - golangci-lint run ./... --fix
      - go test -race ./...
  cleanup:
    cmds:
      - docker ps -aq | xargs -I {} docker rm -f {}
      - docker volume ls -q | xargs -r docker volume rm -f
