version: 3

tasks:
  default:
    cmds:
    - gofmt -w .
    - golangci-lint run ./... --fix
    - go test -race ./...
  cleanup: fly machines ls -a $FLY_APP_NAME --json | jq .[].id -r | xargs -I {} fly machines destroy -f -a $FLY_APP_NAME {}