---
jobs:
  - name: review-code
    plan:
      - task: git-repo
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: "alpine/git" }
          outputs:
            - name: my-repo
          run:
            path: sh
            args:
              - -c
              - |
                  git clone https://github.com/jtarchie/ci my-repo
      - agent: review-code-agent
        prompt: "Review my code changes in the last commit"
        model: openrouter/google/gemini-3.1-flash-lite-preview
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: alpine/git }
          inputs:
            - name: my-repo
          outputs:
            - name: review-result
