assert:
  execution:
    # First job: task succeeds on first attempt (no retries needed)
    - "success-first-attempt"
    # Second job: task succeeds on first attempt (no retries needed)
    - "retry-task"
    # Third job: task fails all 3 attempts, then cleanup runs
    - "fail-all-attempts"
    - "fail-all-attempts"
    - "fail-all-attempts"
    - "cleanup-after-failure"

jobs:
  # Test 1: Normal task without attempts (defaults to 1)
  - name: test-no-attempts
    plan:
      - task: success-first-attempt
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: echo
            args: ["success"]
        assert:
          code: 0
          stdout: "success"
    assert:
      execution:
        - "success-first-attempt"

  # Test 2: Task with attempts=3, eventually succeeds
  - name: test-retry-eventually-succeeds
    plan:
      - task: retry-task
        attempts: 3
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: echo
            args: ["Task executed"]
        assert:
          code: 0

    assert:
      execution:
        # Task runs once and succeeds (no retries needed)
        - "retry-task"

  # Test 3: Task with attempts=3, fails all attempts
  - name: test-all-attempts-fail
    plan:
      - task: fail-all-attempts
        attempts: 3
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: sh
            args:
              - -c
              - |
                  echo "This task always fails"
                  exit 1
        assert:
          code: 1
    on_failure:
      task: cleanup-after-failure
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: busybox
        run:
          path: echo
          args: ["Cleaned up after all attempts failed"]

    assert:
      execution:
        # Task runs 3 times, fails each time
        - "fail-all-attempts"
        - "fail-all-attempts"
        - "fail-all-attempts"
        - "cleanup-after-failure"

  # Test 4: Attempts with ensure hook (ensure runs after all attempts)
  - name: test-attempts-with-ensure
    plan:
      - task: failing-task
        attempts: 2
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: sh
            args: ["-c", "exit 1"]
        assert:
          code: 1
        ensure:
          task: ensure-runs
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: busybox
            run:
              path: echo
              args: ["ensure executed"]
    on_failure:
      task: on-failure-hook
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: busybox
        run:
          path: echo
          args: ["failure hook executed"]

    assert:
      execution:
        - "failing-task"
        - "failing-task"
        - "ensure-runs"
        - "on-failure-hook"

  # Test 5: Attempts=1 (explicit, same as no attempts)
  - name: test-explicit-one-attempt
    plan:
      - task: single-attempt
        attempts: 1
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: echo
            args: ["only runs once"]
        assert:
          code: 0
          stdout: "only runs once"

    assert:
      execution:
        - "single-attempt"
