---
jobs:
  - name: job
    public: true
    plan:
      - task: simple-task
        # this is here for testing purposes
        # probably not for production usage
        assert:
          stdout: Hello world!
          code: 0
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: ["Hello world!"]
