resource_types:
  - name: time
    type: registry-image
    source:
      repository: concourse/time-resource
resources:
  - name: every-30s
    type: time
    source:
      interval: 30s
jobs:
  - name: some-job
    public: true
    plan:
      - get: every-30s
        trigger: true
      - task: simple-task
        config:
          platform: linux
          inputs:
            - name: every-30s
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: sh
            args: ["-c", "cat ./every-30s/timestamp"]
        assert:
          stdout: "2025"
