resource_types:
  - name: mock
    type: registry-image
    source:
      repository: concourse/mock-resource
resources:
  - name: test-resource
    type: mock
    source:
      force_version: "2025"
jobs:
  - name: some-job
    public: true
    plan:
      - get: test-resource
      - task: simple-task
        config:
          platform: linux
          inputs:
            - name: test-resource
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: sh
            args: ["-c", "cat ./test-resource/version"]
        assert:
          stdout: "2025"
