---
jobs:
  - name: some-job
    plan:
      - task: create-file
        assert:
          code: 0
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          outputs:
            - name: mounted-volume
          run:
            path: sh
            args:
              - -c
              - echo "Hello, World!" > ./mounted-volume/hello.txt
      - task: read-file
        assert:
          stdout: Hello, World!
          code: 0
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          inputs:
            - name: mounted-volume
          run:
            path: cat
            args:
              - mounted-volume/hello.txt
